"""empty message

Revision ID: badc25b94254
Revises: 02951d030aee
Create Date: 2023-03-06 14:05:03.029227

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "badc25b94254"
down_revision = "02951d030aee"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("purses", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_active", sa.Boolean(), nullable=False, default=True)
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_active", sa.Boolean(), nullable=False, default=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("is_active")

    with op.batch_alter_table("purses", schema=None) as batch_op:
        batch_op.drop_column("is_active")

    # ### end Alembic commands ###
