service_name: travis-ci
language: python
python:
  - "3.10"
install:
  - pip install -r requirements.txt
  - pip install coverage coveralls
script:
  - coverage run --source=src -m unittest discover -s tests
after_success:
  - coveralls
